wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1648527392
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      2:
      - 1
      - 5
      - 9
      - 41
      3:
      - 2
      4: 3.9.10
      5: 0.12.11
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0006130571238067776
model:
  desc: null
  value: efficientnet_b4
